version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-bank-api
    container_name: backend
    ports:
      - '8005:8005'
    env_file: .env
    environment:
      - GO_ENV=development